In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import plotly.graph_objects as go
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
sns.set_style("darkgrid")
pd.set_option("display.max_columns", None)
pd.options.plotting.backend = "plotly"
warnings.filterwarnings("ignore")

In [2]:

df = pd.read_csv("C://Users/itzha/Downloads/New folder/autism_screening.csv")
df

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0           1         1         1         1         0         0         1   
1           1         1         0         1         0         0         0   
2           1         1         0         1         1         0         1   
3           1         1         0         1         0         0         1   
4           1         0         0         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
699         0         1         0         1         1         0         1   
700         1         0         0         0         0         0         0   
701         1         0         1         1         1         0         1   
702         1         0         0         1         1         0         1   
703         1         0         1         1         1         0         1   

     A8_Score  A9_Score  A10_Score   age gender       ethnicity jundice  \
0           1         0          0  26.0      f  White-European      no   
1           1         0          1  24.0      m          Latino      no   
2           1         1          1  27.0      m          Latino     yes   
3           1         0          1  35.0      f  White-European      no   
4           1         0          0  40.0      f               ?      no   
..        ...       ...        ...   ...    ...             ...     ...   
699         1         1          1  25.0      f  White-European      no   
700         1         0          1  34.0      m        Hispanic      no   
701         1         0          1  24.0      f               ?      no   
702         0         1          1  35.0      m     South Asian      no   
703         1         1          1  26.0      f  White-European      no   

    austim  contry_of_res used_app_before  result     age_desc relation  \
0       no  United States              no     6.0  18 and more     Self   
1      yes         Brazil              no     5.0  18 and more     Self   
2      yes          Spain              no     8.0  18 and more   Parent   
3      yes  United States              no     6.0  18 and more     Self   
4       no          Egypt              no     2.0  18 and more        ?   
..     ...            ...             ...     ...          ...      ...   
699     no         Russia              no     7.0  18 and more     Self   
700     no         Mexico              no     3.0  18 and more   Parent   
701     no         Russia              no     7.0  18 and more        ?   
702     no       Pakistan              no     6.0  18 and more     Self   
703     no         Cyprus              no     8.0  18 and more     Self   

    Class/ASD  
0          NO  
1          NO  
2         YES  
3          NO  
4          NO  
..        ...  
699       YES  
700        NO  
701       YES  
702        NO  
703       YES  

[704 rows x 21 columns]

In [3]:
print(f'Shape of dataframe is: {df.shape}')

Shape of dataframe is: (704, 21)


In [4]:
pd.DataFrame(df.dtypes,
             columns = ["Data Type"])

Data Type
A1_Score            int64
A2_Score            int64
A3_Score            int64
A4_Score            int64
A5_Score            int64
A6_Score            int64
A7_Score            int64
A8_Score            int64
A9_Score            int64
A10_Score           int64
age               float64
gender             object
ethnicity          object
jundice            object
austim             object
contry_of_res      object
used_app_before    object
result            float64
age_desc           object
relation           object
Class/ASD          object

In [5]:
df.describe()

A1_Score    A2_Score    A3_Score    A4_Score    A5_Score    A6_Score  \
count  704.000000  704.000000  704.000000  704.000000  704.000000  704.000000   
mean     0.721591    0.453125    0.457386    0.495739    0.498580    0.284091   
std      0.448535    0.498152    0.498535    0.500337    0.500353    0.451301   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      1.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         A7_Score    A8_Score    A9_Score   A10_Score         age      result  
count  704.000000  704.000000  704.000000  704.000000  702.000000  704.000000  
mean     0.417614    0.649148    0.323864    0.573864   29.698006    4.875000  
std      0.493516    0.477576    0.468281    0.494866   16.507465    2.501493  
min      0.000000    0.000000    0.000000    0.000000   17.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000   21.000000    3.000000  
50%      0.000000    1.000000    0.000000    1.000000   27.000000    4.000000  
75%      1.000000    1.000000    1.000000    1.000000   35.000000    7.000000  
max      1.000000    1.000000    1.000000    1.000000  383.000000   10.000000

In [6]:
pd.DataFrame(df.isnull().sum(), columns=["Missing Values"]).style.bar(color = "#84A9AC")

In [7]:
print(f"Maximum age is data: {df['age'].max()}\n")

print(f"Minimum age is data: {df['age'].min()}")

Maximum age is data: 383.0

Minimum age is data: 17.0


In [8]:
df[df['age'] == df['age'].max()]

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
52         1         0         0         0         0         0         0   

    A8_Score  A9_Score  A10_Score    age gender ethnicity jundice austim  \
52         0         0          0  383.0      f  Pasifika      no     no   

   contry_of_res used_app_before  result     age_desc relation Class/ASD  
52   New Zealand              no     1.0  18 and more     Self        NO

In [9]:
# dropping record number 52
df.drop(index = 52, inplace = True)

# resetting index
df.reset_index(inplace = True)

In [10]:
df['age'] = df['age'].fillna(np.round(df['age'].mean(), 0))

In [11]:
pd.DataFrame(df.isnull().sum(), columns=["Missing Values"])

Missing Values
index                         0
A1_Score                      0
A2_Score                      0
A3_Score                      0
A4_Score                      0
A5_Score                      0
A6_Score                      0
A7_Score                      0
A8_Score                      0
A9_Score                      0
A10_Score                     0
age                           0
gender                        0
ethnicity                     0
jundice                       0
austim                        0
contry_of_res                 0
used_app_before               0
result                        0
age_desc                      0
relation                      0
Class/ASD                     0

In [12]:
for col in df.select_dtypes('O').columns:
    print("-------------------------------")
    print(f'Column name: {col}\n')
    print(f'Unique values:\n{df[col].unique()}\n\n')

-------------------------------
Column name: gender

Unique values:
['f' 'm']


-------------------------------
Column name: ethnicity

Unique values:
['White-European' 'Latino' '?' 'Others' 'Black' 'Asian' 'Middle Eastern '
 'Pasifika' 'South Asian' 'Hispanic' 'Turkish' 'others']


-------------------------------
Column name: jundice

Unique values:
['no' 'yes']


-------------------------------
Column name: austim

Unique values:
['no' 'yes']


-------------------------------
Column name: contry_of_res

Unique values:
['United States' 'Brazil' 'Spain' 'Egypt' 'New Zealand' 'Bahamas'
 'Burundi' 'Austria' 'Argentina' 'Jordan' 'Ireland' 'United Arab Emirates'
 'Afghanistan' 'Lebanon' 'United Kingdom' 'South Africa' 'Italy'
 'Pakistan' 'Bangladesh' 'Chile' 'France' 'China' 'Australia' 'Canada'
 'Saudi Arabia' 'Netherlands' 'Romania' 'Sweden' 'Tonga' 'Oman' 'India'
 'Philippines' 'Sri Lanka' 'Sierra Leone' 'Ethiopia' 'Viet Nam' 'Iran'
 'Costa Rica' 'Germany' 'Mexico' 'Russia' 'Armenia' 'I

In [13]:
df['ethnicity'] = df['ethnicity'].replace('?', 'Others')

In [14]:
df['ethnicity'] = df['ethnicity'].replace('others', 'Others')

In [15]:
df['ethnicity'].unique()

array(['White-European', 'Latino', 'Others', 'Black', 'Asian',
       'Middle Eastern ', 'Pasifika', 'South Asian', 'Hispanic',
       'Turkish'], dtype=object)

In [16]:
df['relation'] = df['relation'].replace('?', df['relation'].mode()[0])

In [17]:
df['relation'].unique()

array(['Self', 'Parent', 'Health care professional', 'Relative', 'Others'],
      dtype=object)

In [18]:
df.head()

index  A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  \
0      0         1         1         1         1         0         0   
1      1         1         1         0         1         0         0   
2      2         1         1         0         1         1         0   
3      3         1         1         0         1         0         0   
4      4         1         0         0         0         0         0   

   A7_Score  A8_Score  A9_Score  A10_Score   age gender       ethnicity  \
0         1         1         0          0  26.0      f  White-European   
1         0         1         0          1  24.0      m          Latino   
2         1         1         1          1  27.0      m          Latino   
3         1         1         0          1  35.0      f  White-European   
4         0         1         0          0  40.0      f          Others   

  jundice austim  contry_of_res used_app_before  result     age_desc relation  \
0      no     no  United States              no     6.0  18 and more     Self   
1      no    yes         Brazil              no     5.0  18 and more     Self   
2     yes    yes          Spain              no     8.0  18 and more   Parent   
3      no    yes  United States              no     6.0  18 and more     Self   
4      no     no          Egypt              no     2.0  18 and more     Self   

  Class/ASD  
0        NO  
1        NO  
2       YES  
3        NO  
4        NO

In [19]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [20]:
#drop multiple columns by name
df.drop(['index'], axis=1, inplace=True)

In [21]:
df['age_desc'] = le.fit_transform(df['age_desc'])

In [22]:
df['gender'].unique()

array(['f', 'm'], dtype=object)

In [23]:
df['gender']= df['gender'].apply(lambda x: 1 if x == 'm' else (0 if x == 'f' else None))

In [24]:
df['jundice'].unique()

array(['no', 'yes'], dtype=object)

In [25]:
df['jundice']= df['jundice'].apply(lambda x: 1 if x == 'yes' else (0 if x == 'no' else None))

In [26]:
df['austim'].unique()

array(['no', 'yes'], dtype=object)

In [27]:
df['austim']= df['austim'].apply(lambda x: 1 if x == 'yes' else (0 if x == 'no' else None))

In [28]:
df['contry_of_res'].unique()

array(['United States', 'Brazil', 'Spain', 'Egypt', 'New Zealand',
       'Bahamas', 'Burundi', 'Austria', 'Argentina', 'Jordan', 'Ireland',
       'United Arab Emirates', 'Afghanistan', 'Lebanon', 'United Kingdom',
       'South Africa', 'Italy', 'Pakistan', 'Bangladesh', 'Chile',
       'France', 'China', 'Australia', 'Canada', 'Saudi Arabia',
       'Netherlands', 'Romania', 'Sweden', 'Tonga', 'Oman', 'India',
       'Philippines', 'Sri Lanka', 'Sierra Leone', 'Ethiopia', 'Viet Nam',
       'Iran', 'Costa Rica', 'Germany', 'Mexico', 'Russia', 'Armenia',
       'Iceland', 'Nicaragua', 'Hong Kong', 'Japan', 'Ukraine',
       'Kazakhstan', 'AmericanSamoa', 'Uruguay', 'Serbia', 'Portugal',
       'Malaysia', 'Ecuador', 'Niger', 'Belgium', 'Bolivia', 'Aruba',
       'Finland', 'Turkey', 'Nepal', 'Indonesia', 'Angola', 'Azerbaijan',
       'Iraq', 'Czech Republic', 'Cyprus'], dtype=object)

In [29]:
df['contry_of_res'] = le.fit_transform(df['contry_of_res'])

In [30]:
df['used_app_before'] = le.fit_transform(df['used_app_before'])

In [31]:
df['relation'] = le.fit_transform(df['relation'])

In [32]:
df['ethnicity'] = le.fit_transform(df['ethnicity'])

In [33]:
df['relation'] = le.fit_transform(df['relation'])

In [34]:
df['Class/ASD'].unique()

array(['NO', 'YES'], dtype=object)

In [35]:
df['Class/ASD']= df['Class/ASD'].apply(lambda x: 1 if x == 'YES' else (0 if x == 'NO' else None))

In [36]:
df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score   age  gender  ethnicity  jundice  austim  \
0         1         0          0  26.0       0          9        0       0   
1         1         0          1  24.0       1          3        0       1   
2         1         1          1  27.0       1          3        1       1   
3         1         0          1  35.0       0          9        0       1   
4         1         0          0  40.0       0          5        0       0   

   contry_of_res  used_app_before  result  age_desc  relation  Class/ASD  
0             64                0     6.0         0         4          0  
1             13                0     5.0         0         4          0  
2             56                0     8.0         0         2          1  
3             64                0     6.0         0         4          0  
4             22                0     2.0         0         4          0

In [37]:
#feature selection

In [38]:
X = df.drop('Class/ASD',axis=1)

In [39]:
X

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0           1         1         1         1         0         0         1   
1           1         1         0         1         0         0         0   
2           1         1         0         1         1         0         1   
3           1         1         0         1         0         0         1   
4           1         0         0         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
698         0         1         0         1         1         0         1   
699         1         0         0         0         0         0         0   
700         1         0         1         1         1         0         1   
701         1         0         0         1         1         0         1   
702         1         0         1         1         1         0         1   

     A8_Score  A9_Score  A10_Score   age  gender  ethnicity  jundice  austim  \
0           1         0          0  26.0       0          9        0       0   
1           1         0          1  24.0       1          3        0       1   
2           1         1          1  27.0       1          3        1       1   
3           1         0          1  35.0       0          9        0       1   
4           1         0          0  40.0       0          5        0       0   
..        ...       ...        ...   ...     ...        ...      ...     ...   
698         1         1          1  25.0       0          9        0       0   
699         1         0          1  34.0       1          2        0       0   
700         1         0          1  24.0       0          5        0       0   
701         0         1          1  35.0       1          7        0       0   
702         1         1          1  26.0       0          9        0       0   

     contry_of_res  used_app_before  result  age_desc  relation  
0               64                0     6.0         0         4  
1               13                0     5.0         0         4  
2               56                0     8.0         0         2  
3               64                0     6.0         0         4  
4               22                0     2.0         0         4  
..             ...              ...     ...       ...       ...  
698             51                0     7.0         0         4  
699             40                0     3.0         0         2  
700             51                0     7.0         0         4  
701             47                0     6.0         0         4  
702             19                0     8.0         0         4  

[703 rows x 20 columns]

In [40]:
y = df['Class/ASD']

In [41]:
y

0      0
1      0
2      1
3      0
4      0
      ..
698    1
699    0
700    1
701    0
702    1
Name: Class/ASD, Length: 703, dtype: int64

In [42]:
from sklearn.feature_selection import SelectKBest

In [43]:
from sklearn.feature_selection import chi2

In [44]:
FIT_FEATURES = SelectKBest(score_func=chi2)

In [45]:
FIT_FEATURES.fit(X,y)

SelectKBest(score_func=<function chi2 at 0x0000023AA3181310>)

In [46]:
SCORE_COL = pd.DataFrame(FIT_FEATURES.scores_,columns =['score value'])

In [47]:
NAME_COL = pd.DataFrame(X.columns)

In [48]:
topr_features = pd.concat([NAME_COL,SCORE_COL],axis=1)

In [49]:
topr_features.columns=['Top Features', 'Score']

In [50]:
topr_features

Top Features       Score
0          A1_Score   17.443289
1          A2_Score   37.107832
2          A3_Score   73.983650
3          A4_Score   78.046165
4          A5_Score  101.379174
5          A6_Score  176.205769
6          A7_Score   50.380460
7          A8_Score   13.743203
8          A9_Score  191.750132
9         A10_Score   44.408393
10              age   39.549483
11           gender    2.224215
12        ethnicity   75.509209
13          jundice    6.583464
14           austim   19.205363
15    contry_of_res    1.686458
16  used_app_before    1.333911
17           result  606.539549
18         age_desc         NaN
19         relation    0.014468

In [51]:
topr_features.nlargest(16,'Score')

Top Features       Score
17       result  606.539549
8      A9_Score  191.750132
5      A6_Score  176.205769
4      A5_Score  101.379174
3      A4_Score   78.046165
12    ethnicity   75.509209
2      A3_Score   73.983650
6      A7_Score   50.380460
9     A10_Score   44.408393
10          age   39.549483
1      A2_Score   37.107832
14       austim   19.205363
0      A1_Score   17.443289
7      A8_Score   13.743203
13      jundice    6.583464
11       gender    2.224215

In [52]:
#drop multiple columns by name
df.drop(['contry_of_res', 'relation', 'age_desc', 'used_app_before'], axis=1, inplace=True)

In [53]:
X = df.drop('Class/ASD',axis=1)

In [54]:
y = df['Class/ASD']

In [55]:
print(X.shape, y.shape)

(703, 16) (703,)


In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state= 10)

In [57]:
from sklearn.naive_bayes import GaussianNB 
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(y_pred)

[0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1
 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0]


In [58]:
from sklearn.metrics import classification_report,confusion_matrix
CM=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",CM)
CR=classification_report(y_test,y_pred)
print("Performance:\n",CR)

Confusion Matrix:
 [[105   2]
 [  3  31]]
Performance:
               precision    recall  f1-score   support

           0       0.97      0.98      0.98       107
           1       0.94      0.91      0.93        34

    accuracy                           0.96       141
   macro avg       0.96      0.95      0.95       141
weighted avg       0.96      0.96      0.96       141



In [59]:
from sklearn.naive_bayes import BernoulliNB
BNG = BernoulliNB()
BNG.fit(X_train,y_train)
BNG_pred = BNG.predict(X_test)
BNG.score(X_test,y_test)

0.950354609929078

In [60]:
CM=confusion_matrix(y_test,BNG_pred)
print("Confusion Matrix:\n",CM)
CR=classification_report(y_test,BNG_pred)
print("Performance:\n",CR)

Confusion Matrix:
 [[103   4]
 [  3  31]]
Performance:
               precision    recall  f1-score   support

           0       0.97      0.96      0.97       107
           1       0.89      0.91      0.90        34

    accuracy                           0.95       141
   macro avg       0.93      0.94      0.93       141
weighted avg       0.95      0.95      0.95       141



In [61]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train,y_train)
MNB_pred = MNB.predict(X_test)
MNB.score(X_test,y_test)

0.8723404255319149

In [62]:
CM=confusion_matrix(y_test,MNB_pred)
print("Confusion Matrix:\n",CM)
CR=classification_report(y_test,MNB_pred)
print("Performance:\n",CR)

Confusion Matrix:
 [[94 13]
 [ 5 29]]
Performance:
               precision    recall  f1-score   support

           0       0.95      0.88      0.91       107
           1       0.69      0.85      0.76        34

    accuracy                           0.87       141
   macro avg       0.82      0.87      0.84       141
weighted avg       0.89      0.87      0.88       141



In [63]:
from sklearn.svm import SVC
SVM_rbf= SVC(kernel='rbf', random_state=10,gamma=3.0,C=1.5)
SVM_classifier=SVM_rbf.fit(X_train,y_train)
SVM_prediction=SVM_classifier.predict(X_test)

In [64]:
CM=confusion_matrix(y_test,SVM_prediction)
print("Confusion Matrix:\n",CM)
CR=classification_report(y_test,SVM_prediction)
print("Performance:\n",CR)

Confusion Matrix:
 [[107   0]
 [ 33   1]]
Performance:
               precision    recall  f1-score   support

           0       0.76      1.00      0.87       107
           1       1.00      0.03      0.06        34

    accuracy                           0.77       141
   macro avg       0.88      0.51      0.46       141
weighted avg       0.82      0.77      0.67       141



In [65]:
from sklearn.ensemble import RandomForestClassifier

In [66]:
Rfc = RandomForestClassifier()
Rfc.fit(X_train,y_train)
Rfc_predict = Rfc.predict(X_test)
Rfc.score(X_test,y_test)

1.0

In [67]:
CM=confusion_matrix(y_test,Rfc_predict)
print("Confusion Matrix:\n",CM)
CR=classification_report(y_test,Rfc_predict)
print("Performance:\n",CR)

Confusion Matrix:
 [[107   0]
 [  0  34]]
Performance:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        34

    accuracy                           1.00       141
   macro avg       1.00      1.00      1.00       141
weighted avg       1.00      1.00      1.00       141



In [68]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier(n_estimators=100,learning_rate=1)
ada.fit(X_train, y_train)
ada.predict(X_test)
ada.score(X_test,y_test)

1.0

In [69]:
from sklearn.linear_model import LinearRegression 
LR = LinearRegression() 
LR.fit(X_train,y_train)
LR_predict = LR.predict(X_test)
LR.score(X_test,y_test)

0.6568952534033123

In [70]:
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score,precision_score,recall_score,f1_score
#f1_score(y_test,LR_predict)

In [71]:
mean_squared_error(y_test,LR_predict)

0.06278432011059555

In [72]:
r2_score(y_test,LR_predict)

0.6568952534033123

In [73]:
from sklearn.linear_model import SGDClassifier
SGD =  SGDClassifier(loss="hinge", penalty="l2")
SGD.fit(X_train,y_train)
SGD_pred = SGD.predict(X_test)
SGD.score(X_test,y_test)

0.8936170212765957

In [74]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
QDA = QuadraticDiscriminantAnalysis()
QDA.fit(X_train,y_train)
QDA_pred = QDA.predict(X_test)
QDA.score(X_test,y_test)

0.624113475177305

In [75]:
svcp = SVC(kernel="poly", degree=3, C=0.025)
svcp.fit(X_train,y_train)
svcp_pred1 = svcp.predict(X_test)
svcp.score(X_test,y_test)

0.7872340425531915

In [76]:
svcr = SVC(kernel="rbf", C=1, gamma=2)
svcr.fit(X_train,y_train)
svcr_pred2 = svcr.predict(X_test)
svcr.score(X_test,y_test)

0.7659574468085106

In [77]:
from sklearn.ensemble import ExtraTreesClassifier
ETC = ExtraTreesClassifier(n_estimators=10, min_samples_split=2)
ETC.fit(X_train,y_train)
ETC_pred = ETC.predict(X_test)
ETC.score(X_test,y_test)

0.9858156028368794

In [78]:
#cathboost
from catboost import CatBoostClassifier
cb = CatBoostClassifier(iterations=100,depth=10,random_state=42,auto_class_weights='Balanced')
cb.fit(X_train,y_train)
cb_pred=cb.predict(X_test)
cb.score(X_test,y_test)

Learning rate set to 0.066538
0:	learn: 0.6611973	total: 160ms	remaining: 15.8s
1:	learn: 0.6323714	total: 172ms	remaining: 8.42s
2:	learn: 0.6102866	total: 183ms	remaining: 5.91s
3:	learn: 0.5663816	total: 185ms	remaining: 4.43s
4:	learn: 0.5366898	total: 188ms	remaining: 3.57s
5:	learn: 0.5189443	total: 198ms	remaining: 3.1s
6:	learn: 0.4825818	total: 200ms	remaining: 2.65s
7:	learn: 0.4676077	total: 211ms	remaining: 2.42s
8:	learn: 0.4406869	total: 212ms	remaining: 2.14s
9:	learn: 0.4244099	total: 224ms	remaining: 2.01s
10:	learn: 0.4016859	total: 225ms	remaining: 1.82s
11:	learn: 0.3876007	total: 239ms	remaining: 1.75s
12:	learn: 0.3664371	total: 244ms	remaining: 1.63s
13:	learn: 0.3552381	total: 258ms	remaining: 1.58s
14:	learn: 0.3325746	total: 259ms	remaining: 1.47s
15:	learn: 0.3083768	total: 260ms	remaining: 1.36s
16:	learn: 0.2901035	total: 261ms	remaining: 1.27s
17:	learn: 0.2793375	total: 270ms	remaining: 1.23s
18:	learn: 0.2654632	total: 275ms	remaining: 1.17s
19:	learn: 0

1.0

In [79]:
from sklearn.linear_model import LogisticRegression 
Reg = LogisticRegression()
Reg.fit(X_train,y_train)
Reg_predict =Reg.predict(X_test)

In [80]:
CM=confusion_matrix(y_test,Reg_predict)
print("Confusion Matrix:\n",CM)
CR=classification_report(y_test,Reg_predict)
print("Performance:\n",CR)

Confusion Matrix:
 [[107   0]
 [  0  34]]
Performance:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        34

    accuracy                           1.00       141
   macro avg       1.00      1.00      1.00       141
weighted avg       1.00      1.00      1.00       141



In [81]:
from sklearn.tree import DecisionTreeClassifier 
tree = DecisionTreeClassifier()
tree.fit(X_train,y_train)
tree_predict = tree.predict(X_test)
tree.score(X_test,y_test)

1.0

In [82]:
CM=confusion_matrix(y_test,tree_predict)
print("Confusion Matrix:\n",CM)
CR=classification_report(y_test,tree_predict)
print("Performance:\n",CR)

Confusion Matrix:
 [[107   0]
 [  0  34]]
Performance:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        34

    accuracy                           1.00       141
   macro avg       1.00      1.00      1.00       141
weighted avg       1.00      1.00      1.00       141



In [83]:
from xgboost import XGBClassifier
xb = XGBClassifier()
xb.fit(X_train,y_train)
xb_pred = xb.predict(X_test)
xb.score(X_test,y_test)

[14:41:59] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


1.0

In [84]:
CM=confusion_matrix(y_test,xb_pred)
print("Confusion Matrix:\n",CM)
CR=classification_report(y_test,xb_pred)
print("Performance:\n",CR)

Confusion Matrix:
 [[107   0]
 [  0  34]]
Performance:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        34

    accuracy                           1.00       141
   macro avg       1.00      1.00      1.00       141
weighted avg       1.00      1.00      1.00       141



0.7562149532710281

0.044609929078014185

0.7562149532710281

In [88]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
scaled_x = scaler.transform(X)

In [89]:
from sklearn.decomposition import PCA
pca = PCA(n_components=15)
pca.fit(scaled_x)
pca_x = pca.transform(scaled_x)
pca_x.shape

(703, 15)

In [90]:
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
 
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
grid.fit(pca_x, y)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.730 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.730 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.730 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.736 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.729 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.915 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.915 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.851 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.929 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.900 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.957 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [91]:
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import mutual_info_classif
svm = SVC(C= 15, gamma= 3.0, kernel= 'rbf')
svm_y_pre = cross_val_predict(svm, pca_x, y, cv=12)
svm_sc = accuracy_score(y, svm_y_pre) * 100
svm_sc = "{:.2f}".format(svm_sc)
print(svm_sc)

77.67
